# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-22 16:33
from __future__ import unicode_literals

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('cheap_talk_trials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='trialchoice',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trialmessage',
        ),
        migrations.AddField(
            model_name='player',
            name='trialchoice1',
            field=otree.db.models.IntegerField(choices=[[0, 'A'], [1, 'B']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trialchoice2',
            field=otree.db.models.IntegerField(choices=[[0, 'A'], [1, 'B']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trialmessage1',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [3, '3'], [5, '5'], [7, '7'], [9, '9']], null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='trialmessage2',
            field=otree.db.models.IntegerField(choices=[[1, '1'], [3, '3'], [5, '5'], [7, '7'], [9, '9']], null=True),
        ),
    ]
